import cv2
import numpy as np
import argparse
import os
import csv
from pathlib import Path

def main():
    """Main function to parse arguments and reconstruct images."""
    parser = argparse.ArgumentParser(
        description=(
            "Reconstructs original images by placing new images onto a canvas\n"
            "according to a log file generated by the cropping script."
        ),
        formatter_class=argparse.RawTextHelpFormatter
    )
    parser.add_argument(
        '-i', '--input_dir', type=str, required=True,
        help='Path to the directory containing the new images to be placed.'
    )
    parser.add_argument(
        '-l', '--log_file', type=str, required=True,
        help='Path to the crop_log.csv file generated by the cropping script.'
    )
    parser.add_argument(
        '-o', '--output_dir', type=str, required=True,
        help='Path to the directory where reconstructed images will be saved.'
    )
    parser.add_argument(
        '--fill_color', type=int, nargs=3, default=[0, 0, 0],
        help='RGB values for the background fill color. Default: 0 0 0 (black).'
    )
    args = parser.parse_args()

    # --- Setup ---
    input_path = Path(args.input_dir)
    output_path = Path(args.output_dir)
    log_path = Path(args.log_file)
    output_path.mkdir(parents=True, exist_ok=True)

    # The fill color is parsed as (R, G, B), but OpenCV uses (B, G, R)
    fill_bgr = args.fill_color[::-1]

    # --- Read Log File ---
    if not log_path.exists():
        print(f"❌ Error: Log file not found at '{log_path}'")
        return
    
    # Create a dictionary to map filenames to their log data for easy lookup
    log_map = {}
    with open(log_path, 'r', newline='') as f:
        reader = csv.DictReader(f)
        for row in reader:
            # Use the output filename from the log as the key
            log_map[row['original_filename']] = row

    # --- Get Input Files ---
    image_extensions = ['.png', '.jpg', '.jpeg', '.bmp', '.tif', '.tiff']
    input_files = [p for p in input_path.iterdir() if p.suffix.lower() in image_extensions]

    if len(log_map) != len(input_files):
        print("⚠️ Warning: The number of images in the input directory does not match the number of entries in the log file.")
        print(f"   Log entries: {len(log_map)}, Image files found: {len(input_files)}")
    
    print(f"Found {len(input_files)} images to process and {len(log_map)} log entries. Proceeding...")

    # --- Processing Loop ---
    for image_to_place_path in input_files:
        try:
            # Get the filename (e.g., '001715_cropped.png')
            image_filename = image_to_place_path.name
            
            # Find the corresponding entry in our log map
            log_entry = log_map.get(image_filename)

            if log_entry is None:
                print(f"   - Skipping '{image_filename}': No matching entry found in log file.")
                continue

            # --- 1. Parse Log Data ---
            orig_w = int(log_entry['original_width'])
            orig_h = int(log_entry['original_height'])
            x1 = int(log_entry['top_left_x'])
            y1 = int(log_entry['top_left_y'])
            crop_size = int(log_entry['crop_size_before_resize'])

            # --- 2. Create Canvas ---
            canvas = np.full((orig_h, orig_w, 3), fill_bgr, dtype=np.uint8)

            # --- 3. Load and Resize Image to Place ---
            image_to_place = cv2.imread(str(image_to_place_path), cv2.IMREAD_UNCHANGED)
            if image_to_place is None:
                print(f"   - Skipping '{image_filename}': Could not be read by OpenCV.")
                continue
            
            if image_to_place.shape[:2] != (crop_size, crop_size):
                image_to_place = cv2.resize(
                    image_to_place, (crop_size, crop_size), interpolation=cv2.INTER_LINEAR
                )

            # --- 4. Place Image on Canvas ---
            # Ensure the image has 3 channels to match the canvas
            if len(image_to_place.shape) == 2:
                image_to_place = cv2.cvtColor(image_to_place, cv2.COLOR_GRAY2BGR)
            # If image has an alpha channel, we only need BGR
            elif image_to_place.shape[2] == 4:
                image_to_place = image_to_place[:, :, :3]

            canvas[y1 : y1 + crop_size, x1 : x1 + crop_size] = image_to_place

            # --- 5. Save Result ---
            # Save using the *original* filename for clarity
            output_filename = log_entry['original_filename']
            output_filepath = output_path / output_filename
            cv2.imwrite(str(output_filepath), canvas)

        except KeyError as e:
            print(f"❌ Error processing {image_to_place_path.name}: Missing expected column {e} in log file.")
        except Exception as e:
            print(f"❌ An unexpected error occurred while processing {image_to_place_path.name}: {e}")

    print(f"\n✅ Reconstruction complete. Images are saved in '{output_path}'.")


if __name__ == '__main__':
    main()